name: climate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.0.3
  http: ^1.2.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  weather_icons: ^3.0.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
